PREFIX time: <http://www.w3.org/2006/time#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rom: <http://www.romedi.fr/romedi/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tox: <http://ontotox.owl#>
PREFIX chemtox: <http://chemontotox.owl/#>
PREFIX chem: <http://chemonto.owl#>

SELECT  ?PAT ?line ?line_label ?line_start_date ?line_stop_date ?PRCKEY
		{
		?PAT chem:followedLine ?line.
		?line time:hasTime ?int_line.
    	?line rdfs:label ?line_label.
		?int_line time:hasBeginning ?line_start.
    	?line_start time:inXSDDate ?line_start_date.
		?int_line time:hasEnd ?line_stop.
    	?line_stop time:inXSDDate ?line_stop_date.
    	?line chem:hasLinePRCkey ?PRCKEY.
    	FILTER(?PAT=<http://chemontotox.owl/#2353176758>)
		}
