PREFIX time: <http://www.w3.org/2006/time#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rom: <http://www.romedi.fr/romedi/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tox: <http://ontotox.owl#>
PREFIX chemtox: <http://chemontotox.owl/#>
PREFIX chem: <http://chemonto.owl#>

SELECT  ?PAT ?line ?line_label ?line_start_date ?line_stop_date ?PRCKEY ?cycle ?cycle_num ?cycle_start_date ?cycle_stop_date ?rom_ing_label ?drug_dose ?is_bolus ?adm_date ?unit_str ?location
		{
		?PAT chem:followedLine ?line.
		?line time:hasTime ?int_line.
    	?line rdfs:label ?line_label.
		?int_line time:hasBeginning ?line_start.
    	?line_start time:inXSDDate ?line_start_date.
		?int_line time:hasEnd ?line_stop.
    	?line_stop time:inXSDDate ?line_stop_date.
    	?line chem:hasLinePRCkey ?PRCKEY.
        ?line chem:isComposedOfCycle ?cycle.
    	?cycle rdfs:label ?cycle_label.
    	?cycle chem:hasCycleNum ?cycle_num.
    	?cycle time:hasTime ?int_cycle.
		?int_cycle time:hasBeginning ?cycle_start.
    	?cycle_start time:inXSDDate ?cycle_start_date.
		?int_cycle time:hasEnd ?cycle_stop.
    	?cycle_stop time:inXSDDate ?cycle_stop_date.
        ?cycle chem:hasAdministration ?adm.
        ?adm chem:hasDrug ?drug_ind.
        ?drug_ind rdfs:label ?drug_label.
        ?drug_ind chem:isRelatedToRomIN ?rom_ing.
        ?rom_ing rdfs:label ?rom_ing_label.
        ?adm chem:hasDoseNorm ?drug_dose.
        ?adm chem:isBolus ?is_bolus.
        ?adm time:hasTime ?day_adm.
        ?day_adm time:inXSDDate ?adm_date.
        ?adm chem:hasUnitSTR ?unit_str.
        ?adm chem:hasCancerLocation ?location.
		}